chore: fix flaky datepicker spec. (#35726)
## Description
In the past we attempted to remove the `DatePickerV2_spec` from flaky
list after successful `/ci-limit-test` runs ([EE PR with
runs](https://github.com/appsmithorg/appsmith-ee/pull/4736)).
But the very next day it had to be added back to the flaky list. There
was certainly a problem which was not getting caught on local and
`ci-limit-test` runs.

Upon observing the [last known failure run of this
spec](https://internal.appsmith.com/app/cypress-dashboard/run-details-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10096251875&attempt=5&selectiontype=test&testsstatus=failed&specsstatus=fail),
this error got highlighted:
> CypressError: Timed out retrying after 100000ms: `cy.wait()` timed out
waiting `100000ms` for the 5th response to the route: `updateLayout`. No
response ever occurred.

Upon further debugging and a loooot of local runs I noticed that even
though we were changing the `Max date` at the end of this spec does not
do anything(on the product UI) and more importantly had no impact on the
test run.

So we removed it. The good thing is that in current [EE
PR](https://github.com/appsmithorg/appsmith-ee/pull/4907) as well there
are no failures.
> PS: I would still be on alert after merging to notice any more
failures and add it back to flaky, if it troubles other team members.


Fixes #`Issue Number`  
_or_  
Fixes `Issue URL`
> [!WARNING]  
> _If no issue exists, please create an issue first, and check with the
maintainers if the issue is valid._

## Automation

/ok-to-test tags="@tag.Datepicker, @tag.Sanity"

### :mag: Cypress test results
<!-- This is an auto-generated comment: Cypress test results  -->
> [!TIP]
> 🟢 🟢 🟢 All cypress tests have passed! 🎉 🎉 🎉
> Workflow run:
<https://github.com/appsmithorg/appsmith/actions/runs/10446454718>
> Commit: b0348f4f13c6b36cb35b0a5fd596513d42ab7837
> <a
href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10446454718&attempt=1"
target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datepicker, @tag.Sanity`
> Spec:
> <hr>Mon, 19 Aug 2024 03:36:10 UTC
<!-- end of auto-generated comment: Cypress test results  -->


## Communication
Should the DevRel and Marketing teams inform users about this change?
- [ ] Yes
- [x] No


<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

## Summary by CodeRabbit

- **Bug Fixes**
- Adjusted the DatePicker component's test to remove the maximum date
constraint, allowing for a broader range of valid dates during testing.
- Revised conditions for tooltip assertions related to date range
validation.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->